### ISSUE TITLE
Still in operation?

### ISSUE THREAD

**Issue by jean-jcrx** [liaan/QwikSwitch-mqtt#1]
Hi, are you still using this yourself? I would like to use this.

- Are their any authentication considerations?

- I see they now have a wifi module as well, still okay to use their usb with RPi rather?

**Comment by liaan** [comment]
Hi, Yes, still use it on my system 

My system only control lights, so not really fussed about security.  But if you want to control garage doors etc, maybe should consider authenticated MQTT etc

I've not tested the wifi module as yet, never needed to.  I use openhab so needed to control my QS somehow and had only USB at that point, thus writing this

**Comment by jean-jcrx** [comment]
Tha ks Karman,

With security I did not mean ‘garage door’ but does the protocol that talks 868MHz from Python to the switch include some kind of security? 

The switch to relay has a synchronization process, how does this work with the Python script? 

Or would someone with a RPi and usb dongle be able to switch my swimming pool on and off?

**Comment by liaan** [comment]
As far I could figure out (I reversed engineered the protocol, QS did not want to release it) there no security.  Maybe there some hidden method todo this, but without QS docs, its going be difficult to guess.

I can press any QS button and it shows on the usb logs so anyone with USB dongle can see the button presses as far I can see.

For the controlling, you need to know the QS receiver unique code to control it, but also, no security, if you know the unique code,  you can control it.

I'll maybe suggest rather use Sonoff device with Tasmota if you don't need dimmers, then you can simply rely  on the wifi for security.

**Comment by jean-jcrx** [comment]
Thanks! I have Sonoffs, reflashed with ESPEasy, using mqtt to Node-RED on RPi. But do not like lights etc on my wifi network.
